<?php 
    $variaveis=array('NOME COMPLETO '=>'nome','DATA DE NASCIMENTO '=>'dt_nascimento','ENDEREÇO DE E-MAIL '=>'email','TELEFONE '=>'tel','CELULAR '=>'cel','ENDEREÇO DE RESIDÊNCIA '=> 'endereco','DATA DO BATISMO'=>'dt_batismo');
    $act=$_GET['act'];
    $x=$_GET['pag'];
    $y=$x+5;
        if($x==0){ 
           $class='class="disabled"';
        }else{
           $class='title=RECUAR';
        }
?>
<div  class="conteudo" >
    <div class="cadastro">
        <?php if($act=='lista'):?>
               <?php 
                  $dao=new Dao();
                  $search=new ModelSearchCriteria();
                  $search->settabela('lt_membros');
                  $lista=$dao->encontre($search);
                  //echo '<pre>';
                  /*
                  foreach($lista as $model){
                     $ano=substr($model->getdt_casamento(),-4,4);
                     $mes=substr($model->getdt_casamento(),-7,2);
                     $dia=substr($model->getdt_casamento(),0,2);
                     $model->setdt_casamento($ano.'-'.$mes.'-'.$dia);
                     /*$ano=substr($model->getdt_nascimento(),-4,4);
                     $mes=substr($model->getdt_nascimento(),-7,2);
                     $dia=substr($model->getdt_nascimento(),0,2);
                     $model->setdt_nascimento($ano.'-'.$mes.'-'.$dia);
                     $ano=substr($model->getdt_ingresso(),-4,4);
                     $mes=substr($model->getdt_ingresso(),-7,2);
                     $dia=substr($model->getdt_ingresso(),0,2);
                     $model->setdt_ingresso($ano.'-'.$mes.'-'.$dia);
                     //print_r($model);die;
                     $dao->grava($model);
                     //echo '<pre>';
                     //print_r($model);
                  }
                  */
                  
                  $titulos=array('Nome','E-mail','Tel.','Nascimento','Endereço','Batismo','Membro desde','Estado Civil','Conjuge','Igreja do Batismo');
                  echo '<div class=paginacao>';
                    echo 'Páginas ';
                    echo ($x/4)+1 .' de ';
                    echo ceil(count($lista)/4);
                  echo '</div>';
                  if(($x/4)+1 == ceil(count($lista)/4)){
                     $class2='class=disabled';
                  }else{
                     $class2='title="AVANÇAR"';
                  }
        echo '<fieldset class=lista><legend><a href='.Utils::createLink('cadastro',array('act'=>'lista','pag'=>$x-4)).' '.$class.' ><< </a> FICHA DE MEMBROS <a href='.Utils::createLink('cadastro',array('act'=>'lista','pag'=>$x+4,'contador'=>count($lista))).' '.$class2.'> >> </a></legend>';
           echo '<table cellspacing=0 border=1>';
                  foreach($lista as $keys => $item){
                    if($x < $keys && $keys < $y){
                       if($item->getnome()){
                        echo '<tr><td class="nome">'.$titulos[0].' </td><td class=dados colspan=3>&nbsp'.$item->getnome().'</td><td class=nome2>'.$titulos[3].' </td><td class=dados>&nbsp'.  ModelValidador::data($item->getdt_nascimento()).'</td></tr>';
                       }
                       if($item->gettel()||$item->getcel()||$item->getemail()){
                          if($item->getemail()){
                             $colspan=2;
                          }else{
                             $colspan=5;
                          }
                        echo '<tr><td class=nome >'.$titulos[2].' </td><td class=dados colspan='.$colspan.'>&nbsp'.$item->gettel();
                        if($item->gettel() && $item->getcel()){echo ' / ';};
                        echo $item->getcel().'</td>';
                       if($item->getemail()){
                        echo '<td class=nome>'.$titulos[1].' </td><td class=dados_ colspan=2>&nbsp'.$item->getemail().'</td></tr>';
                       }
                       }
                       if($item->getestcivil()){
                          if(strstr($item->getestcivil(),'d',true)=="Casa"){
                             $colspan=1;
                          }else{
                             $colspan=5;
                          }
                          echo '<tr><td class=nome>'.$titulos[7].' </td><td class="dados" colspan='.$colspan.'>&nbsp'.$item->getestcivil().'</td>';
                          if(strstr($item->getestcivil(),'d',true)=='Casa'){
                          echo '<td class=nome2>'.$titulos[8].' </td><td class=dados colspan=3>&nbsp'.$item->getconjuge().'</td></tr>';
                          }
                       }
                       if($item->gettipo()){
                        echo '<tr><td class=nome>'.$titulos[4].' </td><td class=dados colspan=5>&nbsp'.$item->gettipo().' '.$item->getendereco().', '.$item->getnumero();
                       }
                       if($item->getcomplemento()){
                         echo ' - '.$item->getcomplemento();
                       }
                       if($item->getbairro()){
                        echo ' - '.$item->getbairro();
                       }
                       if($item->getcidade()){
                          echo '<br>&nbsp'.$item->getcidade();
                       }
                       if($item->getcep()){
                          echo ' - CEP'.$item->getcep();
                       }
                       if($item->getdt_batismo() && $item->getdt_batismo()!='0000-00-00'){
                        echo '<tr><td class="nome col1">'.$titulos[5].' </td><td class="dados col2">&nbsp'.ModelValidador::data($item->getdt_batismo()).'</td><td class="nome3 col3">'.$titulos[9].'</td><td class="dados col4">&nbsp'.$item->getigbatismo().'</td><td class="nome2 col5">'.$titulos[6].' </td><td class="dados col6">'.  ModelValidador::data($item->getdt_ingresso()).'</td></tr>';
                       }
                     echo '<tr><td colspan=6 class=divisao>&nbsp</td><tr>';
                     //$y++;
                    }elseif($keys > $y){
                       break;
                    }
                  }
                       echo '</table>';
      echo '</fieldset>';
               ?>
        <?php elseif($act=='cad'): ?>
        <fieldset class=cadMembros>
            <legend>CADASTRO DE MEMBROS</legend>
         <table>
         <form class="font_1" id="cadastro" action="../paginas/add.php?act=cad" method="POST">
             <?php foreach($variaveis as $keys => $item){
                 if($item=='batizado'){
                    echo '<tr><td align=right>* '.$keys.': </td><td><input type=radio value=S name='.$item.' required> SIM ';
                    echo '<input type=radio value=N name='.$item.'> NÃO</td></tr>';
                 }elseif($item=='email'){
                    echo "<tr><td align=\"right\"> $keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"40\" / ></td></tr>";
                 }else{
                    echo "<tr><td align=\"right\">* $keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"40\" / required></td></tr>";
                 }
             }
             ?>
             <div class="foto">
                  <input type=file>
                  <img />
                  <input type=button class=hide value="Adicionar outro">
             </div>
             <tr><td></td><td align="right"><input type="submit" value="GRAVA">
               &nbsp<input type="reset" value="LIMPA"></td></tr>
         </form>
         </table>
            <span class="info">* campos obrigatórios</span>
        </fieldset>
        <?php endif; ?>
    </div>
</div>